ChatSpaceのDB設計
onnakodomo/chat-space pull request #1
Opened 2019-02-09 04:22 UTC by onnakodomo

2019-02-09 04:40 UTC, TOMARUMARU commented on README.md
> +# groups_usersテーブル
こちらはgroupsテーブルですかね

2019-02-09 04:40 UTC, TOMARUMARU commented on README.md
> +|nickname|text|null: false, unique: true|
ユーザー名で検索をかける機能をつけるのでindexを貼りましょう

2019-02-09 08:44 UTC, onnakodomo commented on README.md
> +# groups_usersテーブル
そうです。
すいません。ミスりました。

2019-02-09 08:44 UTC, onnakodomo commented on README.md
> +|nickname|text|null: false, unique: true|
了解しました!!

2019-02-15 06:19 UTC, onnakodomo commented on README.md
> +|nickname|text|null: false, unique: true|
修正いたしました!!

2019-02-15 06:20 UTC, onnakodomo commented on README.md
> +# groups_usersテーブル
修正いたしました!!

2019-02-15 06:28 UTC, hzak2xx reviewed
scssは＆を使用して書きましょう

2019-02-15 06:30 UTC, onnakodomo commented
<img width="1115" alt="2019-02-15 15 29 56" src="https://user-images.githubusercontent.com/47289315/52838607-9936a100-3136-11e9-8868-ab54e96f608a.png">

2019-02-15 06:34 UTC, onnakodomo commented
返信、ありがとうございます!!
早速、直してみます!!

2019-02-15 08:13 UTC, yuki-uchida commented
次からで結構ですが、修正とマークアップのプルリクは別のものに分けてレビューをもらう様にしましょう。

2019-02-15 08:13 UTC, yuki-uchida requested changes

2019-02-15 08:13 UTC, yuki-uchida commented on README.md
> +|user_id|integer|null: false, foreign_key: true|
外部キーを使う場合にはintegerではなく、refference型とかくと良いです。

2019-02-15 08:22 UTC, onnakodomo commented on README.md
> +|user_id|integer|null: false, foreign_key: true|
ご指摘ありがとうございます!!
早速修正いたします!!

2019-02-15 08:37 UTC, onnakodomo commented
「次からで結構ですが、修正とマークアップのプルリクは別のものに分けてレビューをもらう様にしましょう。」の件に関しまして、

途中でそのミスに気が付き、プッシュ後にメンターの方にも相談しましたが、
次からでいいので、作業する時はブランチを分けることを忘れないようにとご指摘頂きました。
次回から気を付けます。

2019-02-15 08:57 UTC, onnakodomo commented
ご指摘いただききました
「外部キーを使う場合にはintegerではなく、refference型とかくと良い」
に関して、修正を行いました!!
ご確認お願いします。

2019-02-15 09:01 UTC, yuki-uchida commented
LGTMです！

2019-02-15 09:06 UTC, onnakodomo commented
ありがとうございます!!

2019-02-15 09:18 UTC, merged